# Generated by Django 5.1.4 on 2024-12-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_recording', '0002_remove_uploadedfile_file_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_type',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='selected_column',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
