# Generated by Django 5.1.4 on 2025-02-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files_recording", "0003_remove_uploadedfile_file_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfile",
            name="selected_column",
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(upload_to=""),
        ),
        migrations.DeleteModel(
            name="ColumnMapping",
        ),
    ]
