# Generated by Django 5.1.4 on 2025-02-18 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MatchingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("working_file_path", models.CharField(max_length=255)),
                ("reference_file_path", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "W trakcie"),
                            ("COMPLETED", "Zakończone"),
                            ("ERROR", "Błąd"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MatchingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wf_description", models.TextField()),
                ("wf_cell", models.CharField(max_length=10)),
                ("price_target_cell", models.CharField(max_length=10)),
                ("source_info_cell", models.CharField(max_length=10)),
                ("ref_description", models.TextField()),
                ("ref_cell", models.CharField(max_length=10)),
                ("ref_file_name", models.CharField(max_length=255)),
                ("match_score", models.FloatField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="matching.matchingsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-match_score"],
                "indexes": [
                    models.Index(
                        fields=["session", "match_score"],
                        name="matching_ma_session_7d4d19_idx",
                    ),
                    models.Index(
                        fields=["wf_cell"], name="matching_ma_wf_cell_55f571_idx"
                    ),
                ],
            },
        ),
    ]
